# Generated by Django 3.0.8 on 2020-07-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='des',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
