# Generated by Django 3.0.8 on 2020-08-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='todaySpecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to='')),
                ('tagline', models.TextField(blank=True, null=True)),
                ('des', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
