# Generated by Django 3.0.8 on 2020-08-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
